#!/usr/bin/env bash
#
# Generate (and optionally install) the chrony SOCK refclock drop-in for
# chronos-gateway. The refclock `poll` is derived from the gateway's
# sampling.interval_seconds so chronyd gets at least two samples per poll
# (2^poll >= 2 * interval_seconds), which is the cadence that lets chronyd
# reliably select the source and step a large initial offset.
#
# Default is a dry run that prints the recommended drop-in to stdout. Pass
# --install to write it to /etc/chrony/conf.d/chronos.conf and restart chrony.

set -euo pipefail

GATEWAY_YAML="/etc/chronos/gateway.yaml"
DEST="/etc/chrony/conf.d/chronos.conf"
ALLOW=""
INSTALL=0

usage() {
    cat <<'USAGE'
Usage: setup-chrony-refclock.sh [--config FILE] [--allow SUBNET] [--dest FILE] [--install]

  --config FILE   Path to gateway.yaml (default: /etc/chronos/gateway.yaml)
  --allow SUBNET  Add `allow SUBNET` to serve NTP to that network (e.g.
                  10.0.0.0/24). Omit for a host that only syncs itself.
  --dest FILE     Drop-in destination (default: /etc/chrony/conf.d/chronos.conf)
  --install       Write the drop-in and restart chrony (needs sudo). Without it,
                  the recommended config is printed to stdout (dry run).
  -h, --help      Show this help.
USAGE
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --config) GATEWAY_YAML="${2:-}"; shift 2 ;;
        --allow) ALLOW="${2:-}"; shift 2 ;;
        --dest) DEST="${2:-}"; shift 2 ;;
        --install) INSTALL=1; shift ;;
        -h | --help) usage; exit 0 ;;
        *) echo "error: unknown argument: $1" >&2; usage >&2; exit 2 ;;
    esac
done

if [[ ! -r "${GATEWAY_YAML}" ]]; then
    echo "error: cannot read gateway config: ${GATEWAY_YAML}" >&2
    exit 1
fi

# Extract a top-level-or-nested scalar by its (unique) key name. Strips the key,
# surrounding quotes, and any inline comment.
read_key() {
    grep -E "^[[:space:]]*$1:[[:space:]]" "${GATEWAY_YAML}" | head -1 \
        | sed -E "s/^[^:]*:[[:space:]]*//; s/[[:space:]]*#.*$//; s/^\"//; s/\"$//; s/[[:space:]]*$//"
}

interval="$(read_key interval_seconds)"
sock_path="$(read_key sock_path)"
refid="$(read_key refid)"

[[ -n "${interval}" ]] || interval=8
[[ -n "${refid}" ]] || refid="CHRO"
if [[ -z "${sock_path}" ]]; then
    echo "error: chrony.sock_path not found in ${GATEWAY_YAML}" >&2
    exit 1
fi
if ! [[ "${interval}" =~ ^[0-9]+$ ]] || [[ "${interval}" -lt 1 ]]; then
    echo "error: sampling.interval_seconds must be a positive integer (got '${interval}')" >&2
    exit 1
fi

# Smallest poll with 2^poll >= 2 * interval (>= 2 samples per poll).
need=$((2 * interval))
poll=1
period=2
while [[ "${period}" -lt "${need}" ]]; do
    poll=$((poll + 1))
    period=$((period * 2))
done
filter=8

warn() { echo "warning: $*" >&2; }

case "${sock_path}" in
    /run/chrony/*) : ;;
    *) warn "sock_path '${sock_path}' is not under /run/chrony; on Ubuntu/Debian chronyd's AppArmor profile denies creating sockets elsewhere (e.g. /run/chronos/...). Prefer /run/chrony/chronos.sock." ;;
esac

drop_in="$(
    cat <<EOF
# Generated by packaging/setup-chrony-refclock.sh from ${GATEWAY_YAML}.
# interval_seconds=${interval} -> poll ${poll} (2^${poll}=${period}s, >= 2x interval),
# so chronyd gets at least two samples per poll. Re-run this script if you change
# sampling.interval_seconds.
refclock SOCK ${sock_path} refid ${refid} poll ${poll} filter ${filter}
EOF
)"
if [[ -n "${ALLOW}" ]]; then
    drop_in+=$'\n'"allow ${ALLOW}"
fi

if [[ "${INSTALL}" -eq 0 ]]; then
    printf '%s\n' "${drop_in}"
    echo >&2
    echo "# Dry run. Review the above, then install with: $0 --config ${GATEWAY_YAML} --install" >&2
    exit 0
fi

command -v chronyd >/dev/null 2>&1 || warn "chronyd not found on PATH; install chrony (e.g. apt install chrony)."
if ! grep -rqi "makestep" /etc/chrony/ 2>/dev/null; then
    warn "no 'makestep' directive found under /etc/chrony; a large initial offset will be slewed (very slow) instead of stepped. Add 'makestep 1.0 3' to /etc/chrony/chrony.conf."
fi

printf '%s\n' "${drop_in}" | sudo tee "${DEST}" >/dev/null
echo "installed ${DEST}"
sudo systemctl restart chrony
echo "restarted chrony"
echo "verify: chronyc sources   (expect '#* ${refid}' within ~1-3 min)"
echo "        chronyc tracking  (Reference ID ${refid}, Leap status Normal)"
